### ISSUE TITLE
hitting app engine's 60s request deadline often

### ISSUE THREAD

**Issue by snarfed** [snarfed/twitter-atom#6]
i've dug in a bit, but still don't understand why this is happening. traces consistently show that the initial twitter API call(s) happen and returns very early, within the first 1s. when we hit the 60s deadline, we're usually (but not always) in the middle of rendering the [`user_feed.atom`](https://github.com/snarfed/granary/blob/master/granary/templates/user_feed.atom) jinja2 template. so we're evidently spending >59s in either compute (unlikely), or swapped out waiting for other HTTP requests to process, or something.

relevant app engine doc: https://cloud.google.com/appengine/articles/deadlineexceedederrors

also, the line numbers in the `user_feed.atom` parts of stack traces are wrong. [from the jinja2 docs](http://jinja.pocoo.org/docs/dev/faq/#my-tracebacks-look-weird-what-s-happening):
> If the debugsupport module is not compiled and you are using a Python installation without ctypes (Python 2.4 without ctypes, Jython or Google’s AppEngine) Jinja2 is unable to provide correct debugging information and the traceback may be incomplete.

example profile/trace:

<img width="525" alt="screen shot 2017-04-13 at 10 46 20 am" src="https://cloud.githubusercontent.com/assets/778068/25016884/791c12d2-2036-11e7-82ba-3b85ff43ed1d.png">

example logs, with stack traces:

```
162.243.24.13 - - [12/Apr/2017:09:50:15 -0700] "GET /atom?...&list=uhhyeahbret%2Fwikiworld&... HTTP/1.1" 500 - - "Feedbin feed-id:1264986 - 1 subscribers" "twitter-atom.appspot.com" ms=59930 cpu_ms=1429 cpm_usd=1.52103e-7 loading_request=0 instance=... app_engine_release=1.9.48 trace_id=-

09:50:16.041 urlopen GET https://api.twitter.com/1.1/users/show.json?screen_name=uhhyeahbret {}
09:50:16.543 urlopen GET https://api.twitter.com/1.1/lists/statuses.json?include_entities=true&tweet_mode=extended&count=50&slug=wikiworld&owner_screen_name=uhhyeahbret {}
09:51:15.351 Traceback (most recent call last):
...
  File "main.py", line 124</a>, in get
    request_url=self.request.path_url, xml_base='https://twitter.com/'))
  File "local/lib/python2.7/site-packages/granary/atom.py", line 116</a>, in activities_to_atom
    rels=rels or {},
  File "third_party/jinja2-2.6/jinja2/environment.py", line 891, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "local/lib/python2.7/site-packages/granary/templates/user_feed.atom", line 64</a>, in root
    </div>
  File "third_party/jinja2-2.6/jinja2/environment.py", line 929, in new_context
    vars, shared, self.globals, locals)
  File "third_party/jinja2-2.6/jinja2/runtime.py", line 65, in new_context
    if key[:2] == 'l_' and value is not missing:
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.
```

```
07:07:03.081 urlopen GET https://api.twitter.com/1.1/users/show.json?screen_name=TVBig_tw {}
07:07:03.976 urlopen GET https://api.twitter.com/1.1/lists/statuses.json?include_entities=true&tweet_mode=extended&count=50&slug=tvlist&owner_screen_name=TVBig_tw {}
07:08:01.777 Traceback (most recent call last):
...
  File "main.py", line 124, in get
    request_url=self.request.path_url, xml_base='https://twitter.com/'))
  File "local/lib/python2.7/site-packages/granary/atom.py", line 109, in activities_to_atom
    items=[Defaulter(**a) for a in activities],
  File "local/lib/python2.7/site-packages/granary/atom.py", line 99, in __init__
    for k, v in kwargs.items()})
  File "local/lib/python2.7/site-packages/granary/atom.py", line 99, in <dictcomp>
    for k, v in kwargs.items()})
  File "local/lib/python2.7/site-packages/granary/atom.py", line 99, in __init__
    for k, v in kwargs.items()})
  File "local/lib/python2.7/site-packages/granary/atom.py", line 99, in <dictcomp>
    for k, v in kwargs.items()})
  File "local/lib/python2.7/site-packages/granary/atom.py", line 99, in __init__
    for k, v in kwargs.items()})
  File "local/lib/python2.7/site-packages/granary/atom.py", line 98, in <dictcomp>
    k: (Defaulter(**v) if isinstance(v, dict) else v)
DeadlineExceededError: The overall deadline for responding to the HTTP request was exceeded.
```

**Comment by snarfed** [comment]
havent seen this in a while. tentatively closing.
